const emojiData = [
    // Smileys & Emotion
    { char: "😀", name: "grinning face", cat: "smileys" },
    { char: "😃", name: "grinning face with big eyes", cat: "smileys" },
    { char: "😄", name: "grinning face with smiling eyes", cat: "smileys" },
    { char: "😁", name: "beaming face with smiling eyes", cat: "smileys" },
    { char: "😆", name: "grinning squinting face", cat: "smileys" },
    { char: "😅", name: "grinning face with sweat", cat: "smileys" },
    { char: "🤣", name: "rolling on the floor laughing", cat: "smileys" },
    { char: "😂", name: "face with tears of joy", cat: "smileys" },
    { char: "🙂", name: "slightly smiling face", cat: "smileys" },
    { char: "🙃", name: "upside-down face", cat: "smileys" },
    { char: "😉", name: "winking face", cat: "smileys" },
    { char: "😊", name: "smiling face with smiling eyes", cat: "smileys" },
    { char: "😇", name: "smiling face with halo", cat: "smileys" },
    { char: "🥰", name: "smiling face with hearts", cat: "smileys" },
    { char: "😍", name: "smiling face with heart-eyes", cat: "smileys" },
    { char: "🤩", name: "star-struck", cat: "smileys" },
    { char: "😘", name: "face blowing a kiss", cat: "smileys" },
    { char: "😗", name: "kissing face", cat: "smileys" },
    { char: "😚", name: "kissing face with closed eyes", cat: "smileys" },
    { char: "😋", name: "face savoring food", cat: "smileys" },
    { char: "😛", name: "face with tongue", cat: "smileys" },
    { char: "😜", name: "winking face with tongue", cat: "smileys" },
    { char: "🤪", name: "zany face", cat: "smileys" },
    { char: "😝", name: "squinting face with tongue", cat: "smileys" },
    { char: "🤑", name: "money-mouth face", cat: "smileys" },
    { char: "🤗", name: "hugging face", cat: "smileys" },
    { char: "🤭", name: "face with hand over mouth", cat: "smileys" },
    { char: "🤫", name: "shushing face", cat: "smileys" },
    { char: "🤔", name: "thinking face", cat: "smileys" },
    { char: "🤐", name: "zipper-mouth face", cat: "smileys" },
    { char: "🤨", name: "face with raised eyebrow", cat: "smileys" },
    { char: "😐", name: "neutral face", cat: "smileys" },
    { char: "😑", name: "expressionless face", cat: "smileys" },
    { char: "😶", name: "face without mouth", cat: "smileys" },
    { char: "😏", name: "smirking face", cat: "smileys" },
    { char: "😒", name: "unamused face", cat: "smileys" },
    { char: "🙄", name: "face with rolling eyes", cat: "smileys" },
    { char: "😬", name: "grimacing face", cat: "smileys" },
    { char: "🤥", name: "lying face", cat: "smileys" },
    { char: "😌", name: "relieved face", cat: "smileys" },
    { char: "😔", name: "pensive face", cat: "smileys" },
    { char: "😪", name: "sleepy face", cat: "smileys" },
    { char: "🤤", name: "drooling face", cat: "smileys" },
    { char: "😴", name: "sleeping face", cat: "smileys" },
    { char: "😷", name: "face with medical mask", cat: "smileys" },
    { char: "🤒", name: "face with thermometer", cat: "smileys" },
    { char: "🤕", name: "face with head-bandage", cat: "smileys" },
    { char: "🤢", name: "nauseated face", cat: "smileys" },
    { char: "🤮", name: "face vomiting", cat: "smileys" },
    { char: "🤧", name: "sneezing face", cat: "smileys" },
    { char: "🥵", name: "hot face", cat: "smileys" },
    { char: "🥶", name: "cold face", cat: "smileys" },
    { char: "🥴", name: "woozy face", cat: "smileys" },
    { char: "😵", name: "knocked-out face", cat: "smileys" },
    { char: "🤯", name: "exploding head", cat: "smileys" },
    { char: "🤠", name: "cowboy hat face", cat: "smileys" },
    { char: "🥳", name: "partying face", cat: "smileys" },
    { char: "😎", name: "smiling face with sunglasses", cat: "smileys" },
    { char: "🤓", name: "nerd face", cat: "smileys" },
    { char: "🧐", name: "face with monocle", cat: "smileys" },
    { char: "😕", name: "slightly frowning face", cat: "smileys" },
    { char: "😟", name: "worried face", cat: "smileys" },
    { char: "🙁", name: "frowning face", cat: "smileys" },
    { char: "😮", name: "face with open mouth", cat: "smileys" },
    { char: "😯", name: "hushed face", cat: "smileys" },
    { char: "😲", name: "astonished face", cat: "smileys" },
    { char: "😳", name: "flushed face", cat: "smileys" },
    { char: "🥺", name: "pleading face", cat: "smileys" },
    { char: "😦", name: "frowning face with open mouth", cat: "smileys" },
    { char: "😧", name: "anguished face", cat: "smileys" },
    { char: "😨", name: "fearful face", cat: "smileys" },
    { char: "😰", name: "face with sweat", cat: "smileys" },
    { char: "😥", name: "sad but relieved face", cat: "smileys" },
    { char: "😢", name: "crying face", cat: "smileys" },
    { char: "😭", name: "loudly crying face", cat: "smileys" },
    { char: "😱", name: "face screaming in fear", cat: "smileys" },
    { char: "😖", name: "confounded face", cat: "smileys" },
    { char: "😣", name: "persevering face", cat: "smileys" },
    { char: "😞", name: "disappointed face", cat: "smileys" },
    { char: "😓", name: "downcast face with sweat", cat: "smileys" },
    { char: "😩", name: "weary face", cat: "smileys" },
    { char: "😫", name: "tired face", cat: "smileys" },
    { char: "🥱", name: "yawning face", cat: "smileys" },
    { char: "😤", name: "face with steam from nose", cat: "smileys" },
    { char: "😡", name: "pouting face", cat: "smileys" },
    { char: "😠", name: "angry face", cat: "smileys" },
    { char: "🤬", name: "face with symbols on mouth", cat: "smileys" },
    { char: "😈", name: "smiling face with horns", cat: "smileys" },
    { char: "👿", name: "angry face with horns", cat: "smileys" },
    { char: "💀", name: "skull", cat: "smileys" },
    { char: "☠️", name: "skull and crossbones", cat: "smileys" },
    { char: "💩", name: "pile of poo", cat: "smileys" },
    { char: "🤡", name: "clown face", cat: "smileys" },
    { char: "👹", name: "ogre", cat: "smileys" },
    { char: "👺", name: "goblin", cat: "smileys" },
    { char: "👻", name: "ghost", cat: "smileys" },
    { char: "👽", name: "alien", cat: "smileys" },
    { char: "👾", name: "alien monster", cat: "smileys" },
    { char: "🤖", name: "robot", cat: "smileys" },
    { char: "😺", name: "grinning cat", cat: "smileys" },
    { char: "😸", name: "grinning cat with smiling eyes", cat: "smileys" },
    { char: "😻", name: "smiling cat with heart-eyes", cat: "smileys" },
    { char: "😼", name: "cat with wry smile", cat: "smileys" },
    { char: "😽", name: "kissing cat", cat: "smileys" },
    { char: "🙀", name: "weary cat", cat: "smileys" },
    { char: "😿", name: "crying cat", cat: "smileys" },
    { char: "😾", name: "pouting cat", cat: "smileys" },
    { char: "🙈", name: "see-no-evil monkey", cat: "smileys" },
    { char: "🙉", name: "hear-no-evil monkey", cat: "smileys" },
    { char: "🙊", name: "speak-no-evil monkey", cat: "smileys" },
    { char: "💋", name: "kiss mark", cat: "smileys" },
    { char: "💌", name: "love letter", cat: "smileys" },
    { char: "💘", name: "heart with arrow", cat: "smileys" },
    { char: "💝", name: "heart with ribbon", cat: "smileys" },
    { char: "💖", name: "sparkling heart", cat: "smileys" },
    { char: "💗", name: "growing heart", cat: "smileys" },
    { char: "💓", name: "beating heart", cat: "smileys" },
    { char: "💞", name: "revolving hearts", cat: "smileys" },
    { char: "💕", name: "two hearts", cat: "smileys" },
    { char: "💟", name: "heart decoration", cat: "smileys" },
    { char: "❣️", name: "heart exclamation", cat: "smileys" },
    { char: "💔", name: "broken heart", cat: "smileys" },
    { char: "❤️", name: "red heart", cat: "smileys" },
    { char: "🧡", name: "orange heart", cat: "smileys" },
    { char: "💛", name: "yellow heart", cat: "smileys" },
    { char: "💚", name: "green heart", cat: "smileys" },
    { char: "💙", name: "blue heart", cat: "smileys" },
    { char: "💜", name: "purple heart", cat: "smileys" },
    { char: "🤎", name: "brown heart", cat: "smileys" },
    { char: "🖤", name: "black heart", cat: "smileys" },
    { char: "🤍", name: "white heart", cat: "smileys" },

    // Animals & Nature
    { char: "🐶", name: "dog face", cat: "animals" },
    { char: "🐱", name: "cat face", cat: "animals" },
    { char: "🐭", name: "mouse face", cat: "animals" },
    { char: "🐹", name: "hamster face", cat: "animals" },
    { char: "🐰", name: "rabbit face", cat: "animals" },
    { char: "🦊", name: "fox", cat: "animals" },
    { char: "🐻", name: "bear", cat: "animals" },
    { char: "🐼", name: "panda", cat: "animals" },
    { char: "🐨", name: "koala", cat: "animals" },
    { char: "🐯", name: "tiger face", cat: "animals" },
    { char: "🦁", name: "lion", cat: "animals" },
    { char: "🐮", name: "cow face", cat: "animals" },
    { char: "🐷", name: "pig face", cat: "animals" },
    { char: "🐽", name: "pig nose", cat: "animals" },
    { char: "🐸", name: "frog", cat: "animals" },
    { char: "🐵", name: "monkey face", cat: "animals" },
    { char: "🐒", name: "monkey", cat: "animals" },
    { char: "🦍", name: "gorilla", cat: "animals" },
    { char: "🦧", name: "orangutan", cat: "animals" },
    { char: "🐕", name: "dog", cat: "animals" },
    { char: "🦮", name: "guide dog", cat: "animals" },
    { char: "🐩", name: "poodle", cat: "animals" },
    { char: "🐺", name: "wolf", cat: "animals" },
    { char: "🦝", name: "raccoon", cat: "animals" },
    { char: "🐈", name: "cat", cat: "animals" },
    { char: "🐆", name: "leopard", cat: "animals" },
    { char: "🐴", name: "horse face", cat: "animals" },
    { char: "🐎", name: "horse", cat: "animals" },
    { char: "🦄", name: "unicorn", cat: "animals" },
    { char: "🦓", name: "zebra", cat: "animals" },
    { char: "🦌", name: "deer", cat: "animals" },
    { char: "🐂", name: "ox", cat: "animals" },
    { char: "🐃", name: "water buffalo", cat: "animals" },
    { char: "🐄", name: "cow", cat: "animals" },
    { char: "🐖", name: "pig", cat: "animals" },
    { char: "🐗", name: "boar", cat: "animals" },
    { char: "🐏", name: "ram", cat: "animals" },
    { char: "🐑", name: "ewe", cat: "animals" },
    { char: "🐐", name: "goat", cat: "animals" },
    { char: "🐪", name: "camel", cat: "animals" },
    { char: "🐫", name: "two-hump camel", cat: "animals" },
    { char: "🦙", name: "llama", cat: "animals" },
    { char: "🦒", name: "giraffe", cat: "animals" },
    { char: "🐘", name: "elephant", cat: "animals" },
    { char: "🦏", name: "rhinoceros", cat: "animals" },
    { char: "🦛", name: "hippopotamus", cat: "animals" },
    { char: "🐁", name: "mouse", cat: "animals" },
    { char: "🐀", name: "rat", cat: "animals" },
    { char: "🐇", name: "rabbit", cat: "animals" },
    { char: "🐿️", name: "chipmunk", cat: "animals" },
    { char: "🦔", name: "hedgehog", cat: "animals" },
    { char: "🦇", name: "bat", cat: "animals" },
    { char: "🦥", name: "sloth", cat: "animals" },
    { char: "🦦", name: "otter", cat: "animals" },
    { char: "🦨", name: "skunk", cat: "animals" },
    { char: "🦘", name: "kangaroo", cat: "animals" },
    { char: "🦡", name: "badger", cat: "animals" },
    { char: "🐾", name: "paw prints", cat: "animals" },
    { char: "🦃", name: "turkey", cat: "animals" },
    { char: "🐔", name: "chicken", cat: "animals" },
    { char: "🐓", name: "rooster", cat: "animals" },
    { char: "🐣", name: "hatching chick", cat: "animals" },
    { char: "🐤", name: "baby chick", cat: "animals" },
    { char: "🐥", name: "front-facing baby chick", cat: "animals" },
    { char: "🐦", name: "bird", cat: "animals" },
    { char: "🐧", name: "penguin", cat: "animals" },
    { char: "🕊️", name: "dove", cat: "animals" },
    { char: "🦅", name: "eagle", cat: "animals" },
    { char: "🦆", name: "duck", cat: "animals" },
    { char: "🦢", name: "swan", cat: "animals" },
    { char: "🦉", name: "owl", cat: "animals" },
    { char: "🦩", name: "flamingo", cat: "animals" },
    { char: "🦚", name: "peacock", cat: "animals" },
    { char: "🦜", name: "parrot", cat: "animals" },
    { char: "🐊", name: "crocodile", cat: "animals" },
    { char: "🐢", name: "turtle", cat: "animals" },
    { char: "🦎", name: "lizard", cat: "animals" },
    { char: "🐍", name: "snake", cat: "animals" },
    { char: "🐲", name: "dragon face", cat: "animals" },
    { char: "🐉", name: "dragon", cat: "animals" },
    { char: "🦕", name: "sauropod", cat: "animals" },
    { char: "🦖", name: "t-rex", cat: "animals" },
    { char: "🐳", name: "spouting whale", cat: "animals" },
    { char: "🐋", name: "whale", cat: "animals" },
    { char: "🐬", name: "dolphin", cat: "animals" },
    { char: "🐟", name: "fish", cat: "animals" },
    { char: "🐠", name: "tropical fish", cat: "animals" },
    { char: "🐡", name: "blowfish", cat: "animals" },
    { char: "🦈", name: "shark", cat: "animals" },
    { char: "🐙", name: "octopus", cat: "animals" },
    { char: "🐚", name: "spiral shell", cat: "animals" },
    { char: "🐌", name: "snail", cat: "animals" },
    { char: "🦋", name: "butterfly", cat: "animals" },
    { char: "🐛", name: "bug", cat: "animals" },
    { char: "🐜", name: "ant", cat: "animals" },
    { char: "🐝", name: "honeybee", cat: "animals" },
    { char: "🐞", name: "lady beetle", cat: "animals" },
    { char: "🦗", name: "cricket", cat: "animals" },
    { char: "🕷️", name: "spider", cat: "animals" },
    { char: "🕸️", name: "spider web", cat: "animals" },
    { char: "🦂", name: "scorpion", cat: "animals" },
    { char: "🦟", name: "mosquito", cat: "animals" },
    { char: "🦠", name: "microbe", cat: "animals" },
    { char: "💐", name: "bouquet", cat: "animals" },
    { char: "🌸", name: "cherry blossom", cat: "animals" },
    { char: "💮", name: "white flower", cat: "animals" },
    { char: "🏵️", name: "rosette", cat: "animals" },
    { char: "🌹", name: "rose", cat: "animals" },
    { char: "🥀", name: "wilted flower", cat: "animals" },
    { char: "🌺", name: "hibiscus", cat: "animals" },
    { char: "🌻", name: "sunflower", cat: "animals" },
    { char: "🌼", name: "blossom", cat: "animals" },
    { char: "🌷", name: "tulip", cat: "animals" },
    { char: "🌱", name: "seedling", cat: "animals" },
    { char: "🌲", name: "evergreen tree", cat: "animals" },
    { char: "🌳", name: "deciduous tree", cat: "animals" },
    { char: "🌴", name: "palm tree", cat: "animals" },
    { char: "🌵", name: "cactus", cat: "animals" },
    { char: "🌾", name: "sheaf of rice", cat: "animals" },
    { char: "🌿", name: "herb", cat: "animals" },
    { char: "☘️", name: "shamrock", cat: "animals" },
    { char: "🍀", name: "four leaf clover", cat: "animals" },
    { char: "🍁", name: "maple leaf", cat: "animals" },
    { char: "🍂", name: "fallen leaf", cat: "animals" },
    { char: "🍃", name: "leaf fluttering in wind", cat: "animals" },

    // Food & Drink
    { char: "🍏", name: "green apple", cat: "food" },
    { char: "🍎", name: "red apple", cat: "food" },
    { char: "🍐", name: "pear", cat: "food" },
    { char: "🍊", name: "tangerine", cat: "food" },
    { char: "🍋", name: "lemon", cat: "food" },
    { char: "🍌", name: "banana", cat: "food" },
    { char: "🍉", name: "watermelon", cat: "food" },
    { char: "🍇", name: "grapes", cat: "food" },
    { char: "🍓", name: "strawberry", cat: "food" },
    { char: "🍈", name: "melon", cat: "food" },
    { char: "🍒", name: "cherries", cat: "food" },
    { char: "🍑", name: "peach", cat: "food" },
    { char: "🥭", name: "mango", cat: "food" },
    { char: "🍍", name: "pineapple", cat: "food" },
    { char: "🥥", name: "coconut", cat: "food" },
    { char: "🥝", name: "kiwi fruit", cat: "food" },
    { char: "🍅", name: "tomato", cat: "food" },
    { char: "🍆", name: "eggplant", cat: "food" },
    { char: "🥑", name: "avocado", cat: "food" },
    { char: "🥦", name: "broccoli", cat: "food" },
    { char: "🥬", name: "leafy green", cat: "food" },
    { char: "🥒", name: "cucumber", cat: "food" },
    { char: "🌶️", name: "hot pepper", cat: "food" },
    { char: "🌽", name: "ear of corn", cat: "food" },
    { char: "🥕", name: "carrot", cat: "food" },
    { char: "🧄", name: "garlic", cat: "food" },
    { char: "🧅", name: "onion", cat: "food" },
    { char: "🥔", name: "potato", cat: "food" },
    { char: "🍠", name: "roasted sweet potato", cat: "food" },
    { char: "🥐", name: "croissant", cat: "food" },
    { char: "🥯", name: "bagel", cat: "food" },
    { char: "🍞", name: "bread", cat: "food" },
    { char: "🥖", name: "baguette bread", cat: "food" },
    { char: "🥨", name: "pretzel", cat: "food" },
    { char: "🧀", name: "cheese wedge", cat: "food" },
    { char: "🥚", name: "egg", cat: "food" },
    { char: "🍳", name: "cooking", cat: "food" },
    { char: "🧈", name: "butter", cat: "food" },
    { char: "🥞", name: "pancakes", cat: "food" },
    { char: "🧇", name: "waffle", cat: "food" },
    { char: "🥓", name: "bacon", cat: "food" },
    { char: "🥩", name: "cut of meat", cat: "food" },
    { char: "🍗", name: "poultry leg", cat: "food" },
    { char: "🍖", name: "meat on bone", cat: "food" },
    { char: "🌭", name: "hot dog", cat: "food" },
    { char: "🍔", name: "hamburger", cat: "food" },
    { char: "🍟", name: "french fries", cat: "food" },
    { char: "🍕", name: "pizza", cat: "food" },
    { char: "🥪", name: "sandwich", cat: "food" },
    { char: "🥙", name: "stuffed flatbread", cat: "food" },
    { char: "🧆", name: "falafel", cat: "food" },
    { char: "🌮", name: "taco", cat: "food" },
    { char: "🌯", name: "burrito", cat: "food" },
    { char: "🥗", name: "garden salad", cat: "food" },
    { char: "🥘", name: "shallow pan of food", cat: "food" },
    { char: "🍝", name: "spaghetti", cat: "food" },
    { char: "🍜", name: "steaming bowl", cat: "food" },
    { char: "🍲", name: "pot of food", cat: "food" },
    { char: "🍛", name: "curry rice", cat: "food" },
    { char: "🍣", name: "sushi", cat: "food" },
    { char: "🍱", name: "bento box", cat: "food" },
    { char: "🥟", name: "dumpling", cat: "food" },
    { char: "🍤", name: "fried shrimp", cat: "food" },
    { char: "🍙", name: "rice ball", cat: "food" },
    { char: "🍚", name: "cooked rice", cat: "food" },
    { char: "🍘", name: "rice cracker", cat: "food" },
    { char: "🍥", name: "fish cake with swirl", cat: "food" },
    { char: "🥠", name: "fortune cookie", cat: "food" },
    { char: "🍢", name: "oden", cat: "food" },
    { char: "🍡", name: "dango", cat: "food" },
    { char: "🍧", name: "shaved ice", cat: "food" },
    { char: "🍨", name: "ice cream", cat: "food" },
    { char: "🍦", name: "soft serve", cat: "food" },
    { char: "🥧", name: "pie", cat: "food" },
    { char: "🧁", name: "cupcake", cat: "food" },
    { char: "🍰", name: "shortcake", cat: "food" },
    { char: "🎂", name: "birthday cake", cat: "food" },
    { char: "🍮", name: "custard", cat: "food" },
    { char: "🍭", name: "lollipop", cat: "food" },
    { char: "🍬", name: "candy", cat: "food" },
    { char: "🍫", name: "chocolate bar", cat: "food" },
    { char: "🍿", name: "popcorn", cat: "food" },
    { char: "🍩", name: "doughnut", cat: "food" },
    { char: "🍪", name: "cookie", cat: "food" },
    { char: "🌰", name: "chestnut", cat: "food" },
    { char: "🥜", name: "peanuts", cat: "food" },
    { char: "🍯", name: "honey pot", cat: "food" },
    { char: "🥛", name: "milk glass", cat: "food" },
    { char: "☕", name: "hot beverage", cat: "food" },
    { char: "🍵", name: "teacup without handle", cat: "food" },
    { char: "🍶", name: "sake", cat: "food" },
    { char: "🍷", name: "wine glass", cat: "food" },
    { char: "🍸", name: "cocktail glass", cat: "food" },
    { char: "🍹", name: "tropical drink", cat: "food" },
    { char: "🍺", name: "beer mug", cat: "food" },
    { char: "🍻", name: "clinking beer mugs", cat: "food" },
    { char: "🥂", name: "clinking glasses", cat: "food" },
    { char: "🥃", name: "tumbler glass", cat: "food" },
    { char: "🥤", name: "cup with straw", cat: "food" },
    { char: "🧃", name: "beverage box", cat: "food" },
    { char: "🧉", name: "mate", cat: "food" },
    { char: "🧊", name: "ice", cat: "food" },

    // Activities
    { char: "⚽", name: "soccer ball", cat: "activities" },
    { char: "🏀", name: "basketball", cat: "activities" },
    { char: "🏈", name: "american football", cat: "activities" },
    { char: "⚾", name: "baseball", cat: "activities" },
    { char: "🥎", name: "softball", cat: "activities" },
    { char: "🎾", name: "tennis", cat: "activities" },
    { char: "🏐", name: "volleyball", cat: "activities" },
    { char: "🏉", name: "rugby football", cat: "activities" },
    { char: "🎱", name: "pool 8 ball", cat: "activities" },
    { char: "🏓", name: "ping pong", cat: "activities" },
    { char: "🏸", name: "badminton", cat: "activities" },
    { char: "🏒", name: "ice hockey", cat: "activities" },
    { char: "🏑", name: "field hockey", cat: "activities" },
    { char: "🏏", name: "cricket game", cat: "activities" },
    { char: "🥅", name: "goal net", cat: "activities" },
    { char: "⛳", name: "flag in hole", cat: "activities" },
    { char: "🪁", name: "kite", cat: "activities" },
    { char: "🏹", name: "bow and arrow", cat: "activities" },
    { char: "🎣", name: "fishing pole", cat: "activities" },
    { char: "🤿", name: "diving mask", cat: "activities" },
    { char: "🥊", name: "boxing glove", cat: "activities" },
    { char: "🥋", name: "martial arts uniform", cat: "activities" },
    { char: "⛸️", name: "ice skate", cat: "activities" },
    { char: "🎿", name: "skis", cat: "activities" },
    { char: "🛷", name: "sled", cat: "activities" },
    { char: "🥌", name: "curling stone", cat: "activities" },
    { char: "🎯", name: "direct hit", cat: "activities" },
    { char: "🎮", name: "video game", cat: "activities" },
    { char: "🕹️", name: "joystick", cat: "activities" },
    { char: "🎰", name: "slot machine", cat: "activities" },
    { char: "🎲", name: "die", cat: "activities" },
    { char: "🧩", name: "puzzle piece", cat: "activities" },
    { char: "🧸", name: "teddy bear", cat: "activities" },
    { char: "♠️", name: "spade suit", cat: "activities" },
    { char: "♥️", name: "heart suit", cat: "activities" },
    { char: "♦️", name: "diamond suit", cat: "activities" },
    { char: "♣️", name: "club suit", cat: "activities" },
    { char: "♟️", name: "chess pawn", cat: "activities" },
    { char: "🃏", name: "joker", cat: "activities" },
    { char: "🀄", name: "mahjong red dragon", cat: "activities" },
    { char: "🎴", name: "flower playing cards", cat: "activities" },
    { char: "🎭", name: "performing arts", cat: "activities" },
    { char: "🖼️", name: "framed picture", cat: "activities" },
    { char: "🎨", name: "artist palette", cat: "activities" },
    { char: "🧵", name: "thread", cat: "activities" },
    { char: "🧶", name: "yarn", cat: "activities" },

    // Objects
    { char: "💡", name: "light bulb", cat: "objects" },
    { char: "🔦", name: "flashlight", cat: "objects" },
    { char: "🏮", name: "red paper lantern", cat: "objects" },
    { char: "🧱", name: "brick", cat: "objects" },
    { char: "🧭", name: "compass", cat: "objects" },
    { char: "⚖️", name: "balance scale", cat: "objects" },
    { char: "🔋", name: "battery", cat: "objects" },
    { char: "🔌", name: "electric plug", cat: "objects" },
    { char: "💻", name: "laptop", cat: "objects" },
    { char: "🖥️", name: "desktop computer", cat: "objects" },
    { char: "🖨️", name: "printer", cat: "objects" },
    { char: "⌨️", name: "keyboard", cat: "objects" },
    { char: "🖱️", name: "computer mouse", cat: "objects" },
    { char: "🖲️", name: "trackball", cat: "objects" },
    { char: "💽", name: "computer disk", cat: "objects" },
    { char: "💾", name: "floppy disk", cat: "objects" },
    { char: "💿", name: "optical disk", cat: "objects" },
    { char: "📀", name: "dvd", cat: "objects" },
    { char: "🧮", name: "abacus", cat: "objects" },
    { char: "🎥", name: "movie camera", cat: "objects" },
    { char: "🎞️", name: "film frames", cat: "objects" },
    { char: "📽️", name: "film projector", cat: "objects" },
    { char: "🎬", name: "clapper board", cat: "objects" },
    { char: "📺", name: "television", cat: "objects" },
    { char: "📷", name: "camera", cat: "objects" },
    { char: "📸", name: "camera with flash", cat: "objects" },
    { char: "📹", name: "video camera", cat: "objects" },
    { char: "📼", name: "videocassette", cat: "objects" },
    { char: "🔍", name: "magnifying glass tilted left", cat: "objects" },
    { char: "🔎", name: "magnifying glass tilted right", cat: "objects" },
    { char: "🕯️", name: "candle", cat: "objects" },
    { char: "🪔", name: "diya lamp", cat: "objects" },
    { char: "📔", name: "notebook with decorative cover", cat: "objects" },
    { char: "📕", name: "closed book", cat: "objects" },
    { char: "📖", name: "open book", cat: "objects" },
    { char: "📗", name: "green book", cat: "objects" },
    { char: "📘", name: "blue book", cat: "objects" },
    { char: "📙", name: "orange book", cat: "objects" },
    { char: "📚", name: "books", cat: "objects" },
    { char: "📓", name: "notebook", cat: "objects" },
    { char: "📒", name: "ledger", cat: "objects" },
    { char: "📃", name: "page with curl", cat: "objects" },
    { char: "📜", name: "scroll", cat: "objects" },
    { char: "📄", name: "facing up", cat: "objects" },
    { char: "📰", name: "newspaper", cat: "objects" },
    { char: "🗞️", name: "rolled-up newspaper", cat: "objects" },
    { char: "📑", name: "bookmark tabs", cat: "objects" },
    { char: "🔖", name: "bookmark", cat: "objects" },
    { char: "🏷️", name: "label", cat: "objects" },
    { char: "💰", name: "money bag", cat: "objects" },
    { char: "💴", name: "yen banknote", cat: "objects" },
    { char: "💵", name: "dollar banknote", cat: "objects" },
    { char: "💶", name: "euro banknote", cat: "objects" },
    { char: "💷", name: "pound banknote", cat: "objects" },
    { char: "💸", name: "money with wings", cat: "objects" },
    { char: "💳", name: "credit card", cat: "objects" },
    { char: "🧾", name: "receipt", cat: "objects" },
    { char: "💹", name: "chart increasing with yen", cat: "objects" },
    { char: "✉️", name: "envelope", cat: "objects" },
    { char: "📧", name: "e-mail", cat: "objects" },
    { char: "📨", name: "incoming envelope", cat: "objects" },
    { char: "📩", name: "envelope with arrow", cat: "objects" },
    { char: "📤", name: "outbox tray", cat: "objects" },
    { char: "📥", name: "inbox tray", cat: "objects" },
    { char: "📦", name: "package", cat: "objects" },
    { char: "📫", name: "closed mailbox with raised flag", cat: "objects" },
    { char: "📬", name: "open mailbox with raised flag", cat: "objects" },
    { char: "📭", name: "open mailbox with lowered flag", cat: "objects" },
    { char: "📮", name: "postbox", cat: "objects" },
    { char: "🗳️", name: "ballot box with ballot", cat: "objects" },
    { char: "✏️", name: "pencil", cat: "objects" },
    { char: "✒️", name: "black nib", cat: "objects" },
    { char: "🖋️", name: "fountain pen", cat: "objects" },
    { char: "🖊️", name: "pen", cat: "objects" },
    { char: "🖌️", name: "paintbrush", cat: "objects" },
    { char: "🖍️", name: "crayon", cat: "objects" },
    { char: "📝", name: "memo", cat: "objects" },
    { char: "📁", name: "file folder", cat: "objects" },
    { char: "📂", name: "open file folder", cat: "objects" },
    { char: "🗂️", name: "card index dividers", cat: "objects" },
    { char: "📅", name: "calendar", cat: "objects" },
    { char: "📆", name: "tear-off calendar", cat: "objects" },
    { char: "🗒️", name: "spiral notepad", cat: "objects" },
    { char: "🗓️", name: "spiral calendar", cat: "objects" },
    { char: "📇", name: "card index", cat: "objects" },
    { char: "📈", name: "chart increasing", cat: "objects" },
    { char: "📉", name: "chart decreasing", cat: "objects" },
    { char: "📊", name: "bar chart", cat: "objects" },
    { char: "📋", name: "clipboard", cat: "objects" },
    { char: "📌", name: "pushpin", cat: "objects" },
    { char: "📍", name: "round pushpin", cat: "objects" },
    { char: "📎", name: "paperclip", cat: "objects" },
    { char: "🖇️", name: "linked paperclips", cat: "objects" },
    { char: "📏", name: "straight ruler", cat: "objects" },
    { char: "📐", name: "triangular ruler", cat: "objects" },
    { char: "✂️", name: "scissors", cat: "objects" },
    { char: "🗃️", name: "card file box", cat: "objects" },
    { char: "🗄️", name: "file cabinet", cat: "objects" },
    { char: "🗑️", name: "wastebasket", cat: "objects" },
    { char: "🔒", name: "locked", cat: "objects" },
    { char: "🔓", name: "unlocked", cat: "objects" },
    { char: "🔏", name: "locked with pen", cat: "objects" },
    { char: "🔐", name: "locked with key", cat: "objects" },
    { char: "🔑", name: "key", cat: "objects" },
    { char: "🗝️", name: "old key", cat: "objects" },
    { char: "🔨", name: "hammer", cat: "objects" },
    { char: "🪓", name: "axe", cat: "objects" },
    { char: "⛏️", name: "pick", cat: "objects" },
    { char: "⚒️", name: "hammer and pick", cat: "objects" },
    { char: "🛠️", name: "hammer and wrench", cat: "objects" },
    { char: "🗡️", name: "dagger", cat: "objects" },
    { char: "⚔️", name: "crossed swords", cat: "objects" },
    { char: "🔫", name: "pistol", cat: "objects" },
    { char: "🪃", name: "boomerang", cat: "objects" },
    { char: "🏹", name: "bow and arrow", cat: "objects" },
    { char: "🛡️", name: "shield", cat: "objects" },
    { char: "🔧", name: "wrench", cat: "objects" },
    { char: "🪛", name: "screwdriver", cat: "objects" },
    { char: "🔩", name: "nut and bolt", cat: "objects" },
    { char: "⚙️", name: "gear", cat: "objects" },
    { char: "🗜️", name: "clamp", cat: "objects" },
    { char: "⚖️", name: "balance scale", cat: "objects" },
    { char: "🦯", name: "white cane", cat: "objects" },
    { char: "🔗", name: "link", cat: "objects" },
    { char: "⛓️", name: "chains", cat: "objects" },
    { char: "🪝", name: "hook", cat: "objects" },
    { char: "🧰", name: "toolbox", cat: "objects" },
    { char: "🧲", name: "magnet", cat: "objects" },
    { char: "🪜", name: "ladder", cat: "objects" },
    { char: "⚗️", name: "alembic", cat: "objects" },
    { char: "🧪", name: "test tube", cat: "objects" },
    { char: "🧫", name: "petri dish", cat: "objects" },
    { char: "🧬", name: "dna", cat: "objects" },
    { char: "🔬", name: "microscope", cat: "objects" },
    { char: "🔭", name: "telescope", cat: "objects" },
    { char: "📡", name: "satellite antenna", cat: "objects" },
    { char: "💉", name: "syringe", cat: "objects" },
    { char: "🩸", name: "drop of blood", cat: "objects" },
    { char: "💊", name: "pill", cat: "objects" },
    { char: "🩹", name: "adhesive bandage", cat: "objects" },
    { char: "🩺", name: "stethoscope", cat: "objects" },
    { char: "🚪", name: "door", cat: "objects" },
    { char: "🛗", name: "elevator", cat: "objects" },
    { char: "🪞", name: "mirror", cat: "objects" },
    { char: "🪟", name: "window", cat: "objects" },
    { char: "🛏️", name: "bed", cat: "objects" },
    { char: "🛋️", name: "couch and lamp", cat: "objects" },
    { char: "🪑", name: "chair", cat: "objects" },
    { char: "🚽", name: "toilet", cat: "objects" },
    { char: "🪠", name: "plunger", cat: "objects" },
    { char: "🚿", name: "shower", cat: "objects" },
    { char: "🛁", name: "bathtub", cat: "objects" },
    { char: "🪤", name: "mouse trap", cat: "objects" },
    { char: "🪒", name: "razor", cat: "objects" },
    { char: "🧴", name: "lotion bottle", cat: "objects" },
    { char: "🧷", name: "safety pin", cat: "objects" },
    { char: "🧹", name: "broom", cat: "objects" },
    { char: "🧺", name: "basket", cat: "objects" },
    { char: "🧻", name: "roll of paper", cat: "objects" },
    { char: "🧼", name: "soap", cat: "objects" },
    { char: "🧽", name: "sponge", cat: "objects" },
    { char: "🧯", name: "fire extinguisher", cat: "objects" },
    { char: "🛒", name: "shopping cart", cat: "objects" },
    { char: "🚬", name: "cigarette", cat: "objects" },
    { char: "⚰️", name: "coffin", cat: "objects" },
    { char: "🪧", name: "placard", cat: "objects" },
    { char: "⚱️", name: "funeral urn", cat: "objects" },

    // Symbols
    { char: "🏧", name: "atm sign", cat: "symbols" },
    { char: "🚮", name: "litter in bin sign", cat: "symbols" },
    { char: "🚰", name: "potable water", cat: "symbols" },
    { char: "♿", name: "wheelchair symbol", cat: "symbols" },
    { char: "🚹", name: "men's room", cat: "symbols" },
    { char: "🚺", name: "women's room", cat: "symbols" },
    { char: "🚻", name: "restroom", cat: "symbols" },
    { char: "🚼", name: "baby symbol", cat: "symbols" },
    { char: "🚾", name: "water closet", cat: "symbols" },
    { char: "🛂", name: "passport control", cat: "symbols" },
    { char: "🛃", name: "customs", cat: "symbols" },
    { char: "🛄", name: "baggage claim", cat: "symbols" },
    { char: "🛅", name: "left baggage", cat: "symbols" },
    { char: "⚠️", name: "warning", cat: "symbols" },
    { char: "🚸", name: "children crossing", cat: "symbols" },
    { char: "⛔", name: "no entry", cat: "symbols" },
    { char: "🚫", name: "prohibited", cat: "symbols" },
    { char: "🚳", name: "no bicycles", cat: "symbols" },
    { char: "🚭", name: "no smoking", cat: "symbols" },
    { char: "🚯", name: "no littering", cat: "symbols" },
    { char: "🚱", name: "non-potable water", cat: "symbols" },
    { char: "🚷", name: "no pedestrians", cat: "symbols" },
    { char: "📵", name: "no mobile phones", cat: "symbols" },
    { char: "🔞", name: "no one under eighteen", cat: "symbols" },
    { char: "☢️", name: "radioactive", cat: "symbols" },
    { char: "☣️", name: "biohazard", cat: "symbols" },
    { char: "⬆️", name: "up arrow", cat: "symbols" },
    { char: "↗️", name: "up-right arrow", cat: "symbols" },
    { char: "➡️", name: "right arrow", cat: "symbols" },
    { char: "↘️", name: "down-right arrow", cat: "symbols" },
    { char: "⬇️", name: "down arrow", cat: "symbols" },
    { char: "↙️", name: "down-left arrow", cat: "symbols" },
    { char: "⬅️", name: "left arrow", cat: "symbols" },
    { char: "↖️", name: "up-left arrow", cat: "symbols" },
    { char: "↕️", name: "up-down arrow", cat: "symbols" },
    { char: "↔️", name: "left-right arrow", cat: "symbols" },
    { char: "↩️", name: "right arrow curving left", cat: "symbols" },
    { char: "↪️", name: "left arrow curving right", cat: "symbols" },
    { char: "⤴️", name: "right arrow curving up", cat: "symbols" },
    { char: "⤵️", name: "right arrow curving down", cat: "symbols" },
    { char: "🔃", name: "clockwise vertical arrows", cat: "symbols" },
    { char: "🔄", name: "counterclockwise arrows button", cat: "symbols" },
    { char: "🔙", name: "back arrow", cat: "symbols" },
    { char: "🔚", name: "end arrow", cat: "symbols" },
    { char: "🔛", name: "on! arrow", cat: "symbols" },
    { char: "🔜", name: "soon arrow", cat: "symbols" },
    { char: "🔝", name: "top arrow", cat: "symbols" },
    { char: "🛐", name: "place of worship", cat: "symbols" },
    { char: "⚛️", name: "atom symbol", cat: "symbols" },
    { char: "🕉️", name: "om", cat: "symbols" },
    { char: "✡️", name: "star of david", cat: "symbols" },
    { char: "☸️", name: "wheel of dharma", cat: "symbols" },
    { char: "☯️", name: "yin yang", cat: "symbols" },
    { char: "✝️", name: "latin cross", cat: "symbols" },
    { char: "☦️", name: "orthodox cross", cat: "symbols" },
    { char: "☪️", name: "star and crescent", cat: "symbols" },
    { char: "☮️", name: "peace symbol", cat: "symbols" },
    { char: "🕎", name: "menorah", cat: "symbols" },
    { char: "🔯", name: "dotted six-pointed star", cat: "symbols" },
    { char: "♈", name: "aries", cat: "symbols" },
    { char: "♉", name: "taurus", cat: "symbols" },
    { char: "♊", name: "gemini", cat: "symbols" },
    { char: "♋", name: "cancer", cat: "symbols" },
    { char: "♌", name: "leo", cat: "symbols" },
    { char: "♍", name: "virgo", cat: "symbols" },
    { char: "♎", name: "libra", cat: "symbols" },
    { char: "♏", name: "scorpio", cat: "symbols" },
    { char: "♐", name: "sagittarius", cat: "symbols" },
    { char: "♑", name: "capricorn", cat: "symbols" },
    { char: "♒", name: "aquarius", cat: "symbols" },
    { char: "♓", name: "pisces", cat: "symbols" },
    { char: "⛎", name: "ophiuchus", cat: "symbols" },
    { char: "🔀", name: "shuffle tracks button", cat: "symbols" },
    { char: "🔁", name: "repeat button", cat: "symbols" },
    { char: "🔂", name: "repeat single button", cat: "symbols" },
    { char: "▶️", name: "play button", cat: "symbols" },
    { char: "⏩", name: "fast-forward button", cat: "symbols" },
    { char: "⏭️", name: "next track button", cat: "symbols" },
    { char: "⏯️", name: "play-pause button", cat: "symbols" },
    { char: "◀️", name: "reverse button", cat: "symbols" },
    { char: "⏪", name: "fast reverse button", cat: "symbols" },
    { char: "⏮️", name: "last track button", cat: "symbols" },
    { char: "🔼", name: "up-pointing triangle", cat: "symbols" },
    { char: "⏫", name: "fast up button", cat: "symbols" },
    { char: "🔽", name: "down-pointing triangle", cat: "symbols" },
    { char: "⏬", name: "fast down button", cat: "symbols" },
    { char: "⏸️", name: "pause button", cat: "symbols" },
    { char: "⏹️", name: "stop button", cat: "symbols" },
    { char: "⏺️", name: "record button", cat: "symbols" },
    { char: "⏏️", name: "eject button", cat: "symbols" },
    { char: "🎦", name: "cinema", cat: "symbols" },
    { char: "🔅", name: "dim button", cat: "symbols" },
    { char: "🔆", name: "bright button", cat: "symbols" },
    { char: "📶", name: "antenna bars", cat: "symbols" },
    { char: "📳", name: "vibration mode", cat: "symbols" },
    { char: "📴", name: "mobile phone off", cat: "symbols" },
    { char: "♀️", name: "female sign", cat: "symbols" },
    { char: "♂️", name: "male sign", cat: "symbols" },
    { char: "⚧️", name: "transgender symbol", cat: "symbols" },
    { char: "✖️", name: "multiply", cat: "symbols" },
    { char: "➕", name: "plus", cat: "symbols" },
    { char: "➖", name: "minus", cat: "symbols" },
    { char: "➗", name: "divide", cat: "symbols" },
    { char: "♾️", name: "infinity", cat: "symbols" },
    { char: "‼️", name: "double exclamation mark", cat: "symbols" },
    { char: "⁉️", name: "exclamation question mark", cat: "symbols" },
    { char: "❓", name: "question mark", cat: "symbols" },
    { char: "❔", name: "white question mark", cat: "symbols" },
    { char: "❕", name: "white exclamation mark", cat: "symbols" },
    { char: "❗", name: "exclamation mark", cat: "symbols" },
    { char: "〰️", name: "wavy dash", cat: "symbols" },
    { char: "💱", name: "currency exchange", cat: "symbols" },
    { char: "💲", name: "heavy dollar sign", cat: "symbols" },
    { char: "⚕️", name: "medical symbol", cat: "symbols" },
    { char: "♻️", name: "recycling symbol", cat: "symbols" },
    { char: "⚜️", name: "fleur-de-lis", cat: "symbols" },
    { char: "🔱", name: "trident emblem", cat: "symbols" },
    { char: "📛", name: "name badge", cat: "symbols" },
    { char: "🔰", name: "japanese symbol for beginner", cat: "symbols" },
    { char: "⭕", name: "hollow red circle", cat: "symbols" },
    { char: "✅", name: "check mark button", cat: "symbols" },
    { char: "☑️", name: "check box with check", cat: "symbols" },
    { char: "✔️", name: "check mark", cat: "symbols" },
    { char: "❌", name: "cross mark", cat: "symbols" },
    { char: "❎", name: "cross mark button", cat: "symbols" },
    { char: "➰", name: "curly loop", cat: "symbols" },
    { char: "➿", name: "double curly loop", cat: "symbols" },
    { char: "〽️", name: "part alternation mark", cat: "symbols" },
    { char: "✳️", name: "eight-spoked asterisk", cat: "symbols" },
    { char: "✴️", name: "eight-pointed star", cat: "symbols" },
    { char: "❇️", name: "sparkle", cat: "symbols" },
    { char: "©️", name: "copyright", cat: "symbols" },
    { char: "®️", name: "registered", cat: "symbols" },
    { char: "™️", name: "trade mark", cat: "symbols" },
    { char: "#️⃣", name: "keycap number sign", cat: "symbols" },
    { char: "*️⃣", name: "keycap asterisk", cat: "symbols" },
    { char: "0️⃣", name: "keycap digit zero", cat: "symbols" },
    { char: "1️⃣", name: "keycap digit one", cat: "symbols" },
    { char: "2️⃣", name: "keycap digit two", cat: "symbols" },
    { char: "3️⃣", name: "keycap digit three", cat: "symbols" },
    { char: "4️⃣", name: "keycap digit four", cat: "symbols" },
    { char: "5️⃣", name: "keycap digit five", cat: "symbols" },
    { char: "6️⃣", name: "keycap digit six", cat: "symbols" },
    { char: "7️⃣", name: "keycap digit seven", cat: "symbols" },
    { char: "8️⃣", name: "keycap digit eight", cat: "symbols" },
    { char: "9️⃣", name: "keycap digit nine", cat: "symbols" },
    { char: "🔟", name: "keycap: 10", cat: "symbols" },
    { char: "🔠", name: "input latin uppercase", cat: "symbols" },
    { char: "🔡", name: "input latin lowercase", cat: "symbols" },
    { char: "🔢", name: "input numbers", cat: "symbols" },
    { char: "🔣", name: "input symbols", cat: "symbols" },
    { char: "🔤", name: "input latin letters", cat: "symbols" },
    { char: "🅰️", name: "a button (blood type)", cat: "symbols" },
    { char: "🆓", name: "ab button (blood type)", cat: "symbols" },
    { char: "🅱️", name: "b button (blood type)", cat: "symbols" },
    { char: "🆑", name: "cl button", cat: "symbols" },
    { char: "🆒", name: "cool button", cat: "symbols" },
    { char: "🆓", name: "free button", cat: "symbols" },
    { char: "ℹ️", name: "information", cat: "symbols" },
    { char: "🆔", name: "id button", cat: "symbols" },
    { char: "Ⓜ️", name: "circled m", cat: "symbols" },
    { char: "🆕", name: "new button", cat: "symbols" },
    { char: "🆖", name: "ng button", cat: "symbols" },
    { char: "🅾️", name: "o button (blood type)", cat: "symbols" },
    { char: "🆗", name: "ok button", cat: "symbols" },
    { char: "🅿️", name: "p button", cat: "symbols" },
    { char: "🆘", name: "sos button", cat: "symbols" },
    { char: "🆙", name: "up! button", cat: "symbols" },
    { char: "🆚", name: "vs button", cat: "symbols" },
    { char: "🈁", name: "japanese “here” button", cat: "symbols" },
    { char: "🈂️", name: "japanese “service charge” button", cat: "symbols" },
    { char: "🈷️", name: "japanese “monthly amount” button", cat: "symbols" },
    { char: "🈶", name: "japanese “not free of charge” button", cat: "symbols" },
    { char: "🈯", name: "japanese “reserved” button", cat: "symbols" },
    { char: "🉐", name: "japanese “bargain” button", cat: "symbols" },
    { char: "🈹", name: "japanese “discount” button", cat: "symbols" },
    { char: "🈚", name: "japanese “free of charge” button", cat: "symbols" },
    { char: "🈲", name: "japanese “prohibited” button", cat: "symbols" },
    { char: "🉑", name: "japanese “acceptable” button", cat: "symbols" },
    { char: "🈸", name: "japanese “application” button", cat: "symbols" },
    { char: "🈴", name: "japanese “passing grade” button", cat: "symbols" },
    { char: "🈳", name: "japanese “vacancy” button", cat: "symbols" },
    { char: "㊗️", name: "japanese “congratulations” button", cat: "symbols" },
    { char: "㊙️", name: "japanese “secret” button", cat: "symbols" },
    { char: "🈺", name: "japanese “open for business” button", cat: "symbols" },
    { char: "🈵", name: "japanese “no vacancy” button", cat: "symbols" },
    { char: "🔴", name: "red circle", cat: "symbols" },
    { char: "🟠", name: "orange circle", cat: "symbols" },
    { char: "🟡", name: "yellow circle", cat: "symbols" },
    { char: "🟢", name: "green circle", cat: "symbols" },
    { char: "🔵", name: "blue circle", cat: "symbols" },
    { char: "🟣", name: "purple circle", cat: "symbols" },
    { char: "🟤", name: "brown circle", cat: "symbols" },
    { char: "⚫", name: "black circle", cat: "symbols" },
    { char: "⚪", name: "white circle", cat: "symbols" },
    { char: "🟥", name: "red square", cat: "symbols" },
    { char: "🟧", name: "orange square", cat: "symbols" },
    { char: "🟨", name: "yellow square", cat: "symbols" },
    { char: "🟩", name: "green square", cat: "symbols" },
    { char: "🟦", name: "blue square", cat: "symbols" },
    { char: "🟪", name: "purple square", cat: "symbols" },
    { char: "🟫", name: "brown square", cat: "symbols" },
    { char: "⬛", name: "black large square", cat: "symbols" },
    { char: "⬜", name: "white large square", cat: "symbols" },
    { char: "◼️", name: "black medium square", cat: "symbols" },
    { char: "◻️", name: "white medium square", cat: "symbols" },
    { char: "◾", name: "black medium-small square", cat: "symbols" },
    { char: "◽", name: "white medium-small square", cat: "symbols" },
    { char: "▪️", name: "black small square", cat: "symbols" },
    { char: "▫️", name: "white small square", cat: "symbols" },
    { char: "🔶", name: "large orange diamond", cat: "symbols" },
    { char: "🔷", name: "large blue diamond", cat: "symbols" },
    { char: "🔸", name: "small orange diamond", cat: "symbols" },
    { char: "🔹", name: "small blue diamond", cat: "symbols" },
    { char: "🔺", name: "red triangle pointed up", cat: "symbols" },
    { char: "🔻", name: "red triangle pointed down", cat: "symbols" },
    { char: "💠", name: "diamond with a dot", cat: "symbols" },
    { char: "🔘", name: "radio button", cat: "symbols" },
    { char: "🔳", name: "white square button", cat: "symbols" },
    { char: "🔲", name: "black square button", cat: "symbols" }
];

const grid = document.getElementById("grid");
const search = document.getElementById("search");
const categoryTabs = document.getElementById("category-tabs");
const badge = document.getElementById("copied-badge");

let currentCategory = "all";
let itemsPerPage = 300;
let displayedCount = itemsPerPage;

function render(reset = true) {
    if (reset) {
        grid.innerHTML = "";
        displayedCount = itemsPerPage;
    }

    const query = search.value.toLowerCase().trim();

    const filtered = emojiData.filter(e => {
        const matchesQuery = e.name.toLowerCase().includes(query) || e.char.includes(query);
        const matchesCat = currentCategory === "all" || e.cat === currentCategory;
        return matchesQuery && matchesCat;
    });

    const existingButton = document.getElementById("load-more");
    if (existingButton) existingButton.remove();

    if (filtered.length === 0) {
        grid.innerHTML = `<div style="grid-column: 1/-1; text-align: center; padding: 40px; color: var(--text-muted); font-weight: 600;">No emojis found matching "${query}"</div>`;
        return;
    }

    const fragment = document.createDocumentFragment();
    const startIdx = reset ? 0 : displayedCount - itemsPerPage;
    const toDisplay = filtered.slice(startIdx, displayedCount);

    toDisplay.forEach(e => {
        const btn = document.createElement("button");
        btn.className = "emoji-btn";
        btn.title = e.name;
        btn.textContent = e.char;
        btn.addEventListener("click", () => copyEmoji(e.char));
        fragment.appendChild(btn);
    });

    grid.appendChild(fragment);

    if (displayedCount < filtered.length) {
        const loadMore = document.createElement("button");
        loadMore.id = "load-more";
        loadMore.className = "load-more-btn";
        loadMore.textContent = `Load More Emojis (${filtered.length - displayedCount} remaining)`;
        loadMore.onclick = () => {
            displayedCount += itemsPerPage;
            render(false);
        };
        grid.appendChild(loadMore);
    }
}

function copyEmoji(char) {
    navigator.clipboard.writeText(char);
    badge.classList.add("show");
    setTimeout(() => badge.classList.remove("show"), 2000);
}

search.addEventListener("input", () => render(true));

categoryTabs.addEventListener("click", (e) => {
    if (e.target.classList.contains("category-btn")) {
        document.querySelectorAll(".category-btn").forEach(btn => btn.classList.remove("active"));
        e.target.classList.add("active");
        currentCategory = e.target.dataset.category;
        render(true);
    }
});

function initTheme() {
    const themeToggleBtn = document.getElementById('theme-toggle');
    if (!themeToggleBtn) return;
    const icon = themeToggleBtn.querySelector('ion-icon');
    const savedTheme = localStorage.getItem('fossarium-theme');

    const setDarkMode = () => {
        document.documentElement.classList.remove('light-theme');
        if (icon) icon.setAttribute('name', 'sunny-outline');
    };
    const setLightMode = () => {
        document.documentElement.classList.add('light-theme');
        if (icon) icon.setAttribute('name', 'moon-outline');
    };

    if (savedTheme === 'light' || (!savedTheme && window.matchMedia('(prefers-color-scheme: light)').matches)) {
        setLightMode();
    } else {
        setDarkMode();
    }

    themeToggleBtn.addEventListener('click', () => {
        if (document.documentElement.classList.contains('light-theme')) {
            setDarkMode();
            localStorage.setItem('fossarium-theme', 'dark');
        } else {
            setLightMode();
            localStorage.setItem('fossarium-theme', 'light');
        }
    });
}

initTheme();
render();
